name: RandomCommand
author: lrd1122
version: 1.2
main: gx.lrd1122.RandomCommand
softdepend: [PlaceholderAPI]
commands:
  randomcommand:
    description: randomcommand
    usage: /<command>
    aliases: rc